### ISSUE TITLE
useFeatureFlag doesn't re-evaluate on user change

### ISSUE THREAD

**Issue by pdulich** [configcat/react-sdk#27]
### Describe the bug

The `useFeatureFlag` hook doesn't take user changes into account.
If the current user is changed, the result of `useFeatureFlag` stays the same - completely independent of the user change.

Currently, the `useFeatureFlag` implementation uses a `useEffect` hook to call `configCatContext.client.getValueAsync`.
This `useEffect` hook has following dependencies:
- `configCatContext`
- `key`
- `defaultValue`

but not `userState`.
Because of this, the `useEffect` hook doesn't get re-triggered when the user is changed.

### To reproduce

1. Make sure that the ConfigCatLogger logs the evaluations
2. Optional: Create a new feature flag in ConfigCat (in the following lines named `feature-flag-name`). Otherwise, use an already existing flag.
3. Create a new functional component with the following implementation:
```
export const FeatureFlagBugPresentation = () => {
    const [customAttribute, setCustomAttribute] = useState<string>('old value');
    useEffect(() => {
        setCustomAttribute('new value');
    }, []);

    const userObject = useMemo(
        () => new User('user-id', 'user@email.com', 'DE', { customAttribute }),
        [customAttribute],
    );

    console.log(`Evaluating feature flag for user with customAttribute = ${userObject.custom?.customAttribute}`);
    const flagState = useFeatureFlag('feature-flag-name', false, userObject);

    return flagState
        ? <span>Active</span>
        : <span>Inactive</span>;
};
```
3. Use the component in the application
4. Watch the logs. 

There will be two lines printed:
  * `Evaluating feature flag for user with customAttribute = old value`
  * `Evaluation feature flag for user with customAttribute = new value`

But ConfigCat logs only one evaluation 
`ConfigCat - INFO - Evaluate 'dummy'  User : {"custom":{"customAttribute":"old value"} ...`
There is no evaluation with the new `customAttribute` value.

### Expected behavior

When the user of a user-based feature flag is changed the feature flag should re-evaluate with the changed user and return the respective flag state.

### Screenshots

--None--

**Comment by laliconfigcat** [comment]
Hello @theMunichDev ,

Thanks for reaching out. We are checking the issue and we will get back to you.

**Comment by laliconfigcat** [comment]
Hello @theMunichDev ,

I just released v2.3.0 of the SDK. Could you please try it and check if it is solving your problem or not? I tested it and it seems to be alright.

Cheers,
Lali

**Comment by theMunichDev** [comment]
👍🏻 Yes, I will write it out.

**Comment by theMunichDev** [comment]
Hey @laliconfigcat ,

I just tested it. Seems to work. 👍🏻 
The flag is re-evaluated and I don't need to use `useMemo` or the like for the `user` object.

Greets,
Pascal

**Comment by hakubo** [comment]
There is one issue with the implementation I found. 

When user changes - useFeatureFlag returns stale FF value and requires one more rerender to return correct value.

Normally not an issue, but we want to log values and this causes the value to be logged twice.
