### ISSUE TITLE
Warning about existing client instance

### ISSUE THREAD

**Issue by gregoralbrecht** [configcat/react-sdk#65]
### Describe the bug

I've followed [this guide](https://configcat.com/docs/sdk-reference/react/#creating-the-configcat-client) and set up a ConfigCat Client in our NextJS application (with React `v18.2.0`) like this:

`_app.tsx`
```tsx
// ...
<ConfigCatProvider
  sdkKey={process.env.NEXT_PUBLIC_CONFIG_CAT}
  options={{
    logger: createConsoleLogger(LogLevel.Info),
  }}
>
// ...
```

However, my browser console consistently shows the following warning:
```
ConfigCat - WARN - [3000] There is an existing client instance for the specified SDK Key. No new client instance will be created and the specified options are ignored. Returning the existing client instance. SDK Key: 'configcat-sdk-1/{OUR_KEY}. 
```

### To reproduce

1. Set up ConfigCat within a NextJS app. 
2. See the warning.
3. If you remove the `options`, the warning disappears.

### Expected behavior

No warning in browser console.

**Comment by adams85** [comment]
Hi @gregoralbrecht,

Does the problem occur in both development and production mode?

If it's development-only, it's probably caused by [React's strict mode](https://react.dev/reference/react/StrictMode). In that case, you can safely ignore this warning.

**Comment by gregoralbrecht** [comment]
Hey @adams85, thanks for getting back to me so quickly. I should've mentioned that, my bad!

We're using Strict Mode and it's only happening in Development mode. I suspect it's because of that, but I was still wondering if there's any way to either disable the warning or not show it? It takes up quite a chunk of space in our browser consoles. Apologies if my request is ridiculous 😅

**Comment by adams85** [comment]
No problem.

It's possible to disable this warning like this:

```jsx
class CustomConsoleLogger {
  constructor(logLevel) {
    this.consoleLogger = configcat.createConsoleLogger(logLevel);
  }

  log(level, eventId, message, exception) {
    // Filter events here.
    if (eventId === 3000) {
      return;
    }

    this.consoleLogger.log(level, eventId, message, exception);
  }
}

<ConfigCatProvider
  sdkKey={process.env.NEXT_PUBLIC_CONFIG_CAT}
  options={{
    logger: new CustomConsoleLogger(configcat.LogLevel.Warn)
  }}
>
```

This is going to be less cumbersome in the future as we plan to add a log filter callback to the client options. But for now, implementing a custom logger is the only option.
